name: shop_in
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  firebase_database: ^10.4.11
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3+1
  http: ^0.13.3
  riverpod: ^1.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/shop_logo.png

