// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDRdjE9wfmbBQOyIZvvTtR22e8T1kC7Jk',
    appId: '1:367266432707:web:a56a9217a4b2b3d2d44476',
    messagingSenderId: '367266432707',
    projectId: 'shop-in-project',
    authDomain: 'shop-in-project.firebaseapp.com',
    storageBucket: 'shop-in-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQmVT60Ur4XCuwx9l-crDV0Mu78gHfqok',
    appId: '1:367266432707:android:78be017f1edc111ad44476',
    messagingSenderId: '367266432707',
    projectId: 'shop-in-project',
    storageBucket: 'shop-in-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr3MDwyiGGnX40yLaYP1YM-2RYqKXii8U',
    appId: '1:367266432707:ios:d06cda9ce6b6542dd44476',
    messagingSenderId: '367266432707',
    projectId: 'shop-in-project',
    storageBucket: 'shop-in-project.appspot.com',
    iosBundleId: 'com.example.shopIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr3MDwyiGGnX40yLaYP1YM-2RYqKXii8U',
    appId: '1:367266432707:ios:50482da810a4e1c3d44476',
    messagingSenderId: '367266432707',
    projectId: 'shop-in-project',
    storageBucket: 'shop-in-project.appspot.com',
    iosBundleId: 'com.example.shopIn.RunnerTests',
  );
}
